# Generated by Django 4.2.6 on 2024-02-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mob', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('prof', models.CharField(max_length=100)),
                ('eid', models.CharField(max_length=100)),
            ],
        ),
    ]
