# Generated by Django 5.0.2 on 2024-02-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
